CREATE TABLE watch_log (
    id             BIGINT       NOT NULL AUTO_INCREMENT,
    member_id      BIGINT       NOT NULL,
    game_id        BIGINT,
    game_season    SMALLINT,
    venue          VARCHAR(100),
    watch_type     VARCHAR(20)  NOT NULL,
    cheering_team  VARCHAR(30)  NOT NULL,
    result         VARCHAR(20)  NOT NULL,
    title          VARCHAR(200),
    content        TEXT,
    seat_grade     VARCHAR(50),
    seat_section   VARCHAR(20),
    seat_row       VARCHAR(10),
    seat_number    VARCHAR(10),
    companions     VARCHAR(200),
    mood           VARCHAR(20),
    ticket_cost    INT,
    food_cost      INT,
    transport_cost INT,
    weather_condition VARCHAR(20),
    temperature    DECIMAL(4, 1),
    is_public      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     DATETIME(6)  NOT NULL,
    updated_at     DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_watch_log_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_watch_log_game   FOREIGN KEY (game_id)   REFERENCES game (id),
    INDEX idx_watch_log_member_created (member_id, created_at DESC),
    INDEX idx_watch_log_public (is_public, created_at DESC)
);
